In [1]:
import numpy as np
from scipy import linalg as LA
import itertools
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
#mock data #imagine rows are syllables and columns are mice
#change values and/or size of array to see how it effects the eigenvectors/eigenvalues 

#in our mock data we have 4 mice that produce 3 syllables
mockdata = np.array([  
        [5.1,5, 13],
        [5,9,28],
        [4,6,2],
        [5,8,16],])
display(mockdata)

array([[ 5.1,  5. , 13. ],
       [ 5. ,  9. , 28. ],
       [ 4. ,  6. ,  2. ],
       [ 5. ,  8. , 16. ]])

In [3]:
#centering the data
mockdata -= np.mean(mockdata, axis = 0)  
display(mockdata)

array([[  0.325,  -2.   ,  -1.75 ],
       [  0.225,   2.   ,  13.25 ],
       [ -0.775,  -1.   , -12.75 ],
       [  0.225,   1.   ,   1.25 ]])

In [4]:
#calculate covariance matrix
cov = np.cov(mockdata, rowvar = False)

display(cov)

array([[  0.26916667,   0.26666667,   4.19166667],
       [  0.26666667,   3.33333333,  14.66666667],
       [  4.19166667,  14.66666667, 114.25      ]])

In [5]:
#get eigenvectors and eigenvalues
evals , evecs = LA.eigh(cov)

#formatting and SORT by eigenvalues (aka sort by how much variance each eigen vector explains)
idx = np.argsort(evals)[::-1]
evecs = evecs[:,idx]
evals = evals[idx]

display(evecs)
display(evals)

array([[-0.03609448,  0.19792345,  0.9795527 ],
       [-0.12874215, -0.9729446 ,  0.19184437],
       [-0.99102101,  0.11918519, -0.06059902]])

array([1.16307993e+02, 1.48242723e+00, 6.20799178e-02])

In [6]:
#this is your data represented as PCS 
mockdata_represented_as_pcs = np.dot(mockdata, evecs)
display(mockdata_represented_as_pcs)

array([[  1.98004036,   1.80164023,   0.04071418],
       [-13.39663397,  -0.32215261,  -0.19884889],
       [ 12.79223328,  -0.70005729,  -0.17836024],
       [ -1.37563967,  -0.77943033,   0.33649495]])