In [1]:
import scipy.io as sio
import h5py
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os
from moseq2_viz.model.util import (get_transition_matrix,
                                   parse_model_results,
                                   relabel_by_usage)
from moseq2_viz.util import parse_index
from moseq2_viz.scalars.util import scalars_to_dataframe
from moseq2_viz.model.dist import get_behavioral_distance

In [2]:
file_path = '/Users/cakiti/Dropbox (Uchida Lab)/Korleki Akiti/Behavior/Standard setup/CombineAnalysis/Just-in-case files/Dataset_20190723/'

# load in the model and the index to the extracted data
model_file = os.path.join(file_path,'my_model.p') 
index_file = os.path.join(file_path,'moseq2-index.yaml')


# Save file directory
save_directory=os.path.join(file_path, 'MoSeqDataFrame_test.mat')

In [3]:
model_results = parse_model_results(model_file)
index, sorted_index = parse_index(index_file)

In [4]:
display(model_results)

{'loglikes': [[6840290.865722656]],
 'labels': [array([-5, -5, -5, ..., 40, 40, 40], dtype=int16),
  array([-5, -5, -5, ..., 10, 10, 10], dtype=int16),
  array([-5, -5, -5, ..., 36, 36, 36], dtype=int16),
  array([-5, -5, -5, ..., 82, 82, 82], dtype=int16),
  array([-5, -5, -5, ..., 60, 60, 60], dtype=int16),
  array([-5, -5, -5, ..., 11, 11, 11], dtype=int16),
  array([-5, -5, -5, ..., 94, 94, 94], dtype=int16),
  array([-5, -5, -5, ..., 93, 93, 93], dtype=int16),
  array([-5, -5, -5, ..., 28, 28, 28], dtype=int16),
  array([-5, -5, -5, ..., 21, 21, 21], dtype=int16),
  array([-5, -5, -5, ..., 27, 27, 27], dtype=int16),
  array([-5, -5, -5, ..., 55, 55, 55], dtype=int16),
  array([-5, -5, -5, ...,  6,  6,  6], dtype=int16),
  array([-5, -5, -5, ..., 32, 32, 32], dtype=int16),
  array([-5, -5, -5, ..., 32, 32, 32], dtype=int16),
  array([-5, -5, -5, ..., 43, 43, 43], dtype=int16),
  array([-5, -5, -5, ..., 85, 85, 85], dtype=int16),
  array([-5, -5, -5, ..., 38, 38, 38], dtype=int16),


In [ ]:
# retrieves behavioral distance using AR matrices
dist = get_behavioral_distance(sorted_index, 
                               model_file, 
                               distances=['ar[init]'], 
                               max_syllable=None,
                               sort_labels_by_usage=True) # FALSE ########################

# packs data into a dataframe, including all scalars and model labels (note that -5 is a fill value, ignore for all downstream analysis)
df = scalars_to_dataframe(sorted_index, include_model=model_file)

sorted_labels = relabel_by_usage(model_results['labels'])[0]

save_dict=df.to_dict("list")
save_dict['syllable_dis']=dist['ar[init]']
save_dict['sorted_labels']=sorted_labels
save_dict['labels']=model_results['labels']
save_dict['session_uuid']=model_results['keys']

sio.savemat(save_directory, {'MoSeqDataFrame':save_dict})